// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQypVFGBUJ-QxyfP7MoWfsxvvlFe4-iro',
    appId: '1:974216609270:web:127bf6e7bc60e9b001dbd7',
    messagingSenderId: '974216609270',
    projectId: 'math-solver-60ac1',
    authDomain: 'math-solver-60ac1.firebaseapp.com',
    storageBucket: 'math-solver-60ac1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEM1wGYdvmCgqX3dF5RGwSNo2Vysphsvo',
    appId: '1:974216609270:android:f3398ea8301a7c1401dbd7',
    messagingSenderId: '974216609270',
    projectId: 'math-solver-60ac1',
    storageBucket: 'math-solver-60ac1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWbYS0R1YcI8LAX2zvAZEhC0aiEC-MgQQ',
    appId: '1:974216609270:ios:d235d91ad8fc786e01dbd7',
    messagingSenderId: '974216609270',
    projectId: 'math-solver-60ac1',
    storageBucket: 'math-solver-60ac1.appspot.com',
    iosBundleId: 'com.example.mathSolverApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWbYS0R1YcI8LAX2zvAZEhC0aiEC-MgQQ',
    appId: '1:974216609270:ios:9d2e9812ad172dfb01dbd7',
    messagingSenderId: '974216609270',
    projectId: 'math-solver-60ac1',
    storageBucket: 'math-solver-60ac1.appspot.com',
    iosBundleId: 'com.example.mathSolverApp.RunnerTests',
  );
}
